### PR TITLE
fix: extend eslint-recommended

### PR DESCRIPTION
**Pull request by marshall**
extend `eslint-recommended` to capture more common code errors

see https://github.com/goabstract/ui/pull/4435 for the how and why

### CODE REVIEW

**Comment by nathasha** [comment]
@marshall - Our sdk is using the same eslint config. You might want to check that as well. 
https://github.com/goabstract/abstract-sdk/blob/master/package.json#L82

**Comment by marshall** [comment]
@nathasha thanks for the heads up! it looks like it is pinned to `^4.1.0`, and has been for a while, so this change won't affect the SDK unless we change the dependent version. do you think we should update abstract-sdk to the latest to match?

**Comment by nathasha** [comment]
@marshall, in that case I don't think we need to update the sdk. I think we probably should bump the version for this change in here

> @nathasha thanks for the heads up! it looks like it is pinned to `^4.1.0`, and has been for a while, so this change won't affect the SDK unless we change the dependent version. do you think we should update abstract-sdk to the latest to match?

In that case, I don't think we need to update abstract-sdk. 

We should probably bump the version in this package for this update, right?

**Comment by marshall** [comment]
> We should probably bump the version in this package for this update, right?
 sorry the slow reply here! yes, I will bump the version on master and publish to npm once the PR is merged (per docs), and then update the UI PR with the new version before landing it

**Comment by marshall** [comment]
see downstream UI PR here: https://github.com/goabstract/ui/pull/4435

**Review by rickharris — APPROVED** [review]

**Pull request merged**
