### PR TITLE
Enforce curly braces for all if statements

### PR DESCRIPTION
**Pull request by rickharris**
Enables https://eslint.org/docs/rules/curly, which is auto fixable.

Came about from https://github.com/goabstract/ui/pull/661#discussion_r266635536, I'm interested to hear what others on the team think about this.

I like relying on prettier for any stylistic formatting, I see this as a kind of rule that I wish prettier didn't give as much flexibility on. And since this is an auto-fixable rule, I think we can view this as kind of an extension of prettier.

### CODE REVIEW

**Comment by tommoor** [comment]
I think the reason prettier offers flexibility here is because both ways make sense depending on the scenario. For simple guards, for example, an inline return is often much cleaner and easier to parse.

I think we'd have to see it applied against the codebase to really make a decision but my gut is that there will be quite a few places that become objectively "worse" by enforcing this.

**Comment by rickharris** [comment]
I've definitely written plenty of one-liners, but I struggle to think of when it's objectively better and more readable.

**Comment by thenanyu** [comment]
I'm fine with merging this in and if we discover a case where this makes it worse, we can re-examine at that point

**Comment by rickharris** [comment]
Superseded by https://github.com/goabstract/eslint-config/pull/19

**Pull request closed without merging**
