### PR TITLE
Bump versions for prettier and eslint-prettier

### PR DESCRIPTION
**Pull request by taylorlapeyre**
This is to support peer dependencies on https://github.com/goabstract/ui/pull/57

### CODE REVIEW

**Comment by rickharris** [comment]
I'm pretty confused about what's happening on CI right now. We don't even have a CircleCI config file in this project.

**Comment by taylorlapeyre** [comment]
@rickharris I think we need to disable CI on this repo..? I have no idea why it's running

**Comment by rickharris** [comment]
> eslint-plugin-prettier@3.0.0" has incorrect peer dependency "eslint@>= 5.0.0"

Seeing this when running `yarn install` on this branch now, seems like we might need to upgrade eslint as well

**Comment by rickharris** [comment]
Just realized something else... we're going to have to set this up to run in CI because we don't have publish rights on NPM on our individual computers anymore. Sorry this is really snowballing!

**Comment by tommoor** [comment]
Hmm, wasn't aware the SDK was using it. So, I guess we have three choices:

- Keep it separate here and setup CircleCI / NPM publishing
- Move to monorepo and setup NPM publishing
- Move to monorepo and give SDK it's own eslint setup

**Pull request closed without merging**
